# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payments/v1/common.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18payments/v1/common.proto\x12\x0bpayments.v1\"/\n\x05Money\x12\x14\n\x0c\x61mount_cents\x18\x01 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"j\n\x07\x41\x64\x64ress\x12\r\n\x05line1\x18\x01 \x01(\t\x12\r\n\x05line2\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\t\x12\x13\n\x0bpostal_code\x18\x05 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x06 \x01(\t\"{\n\rEventMetadata\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63\x61usation_id\x18\x03 \x01(\t\x12*\n\ncreated_at\x18\x04 \x01(\x0b\x32\x16.payments.v1.Timestamp\"d\n\x0c\x45rrorDetails\x12\x12\n\nerror_code\x18\x01 \x01(\t\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x14\n\x0cis_retryable\x18\x03 \x01(\x08\x12\x13\n\x0bretry_count\x18\x04 \x01(\x05*\x93\x01\n\nVoidStatus\x12\x1b\n\x17VOID_STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13VOID_STATUS_PENDING\x10\x01\x12\x19\n\x15VOID_STATUS_COMPLETED\x10\x02\x12\x16\n\x12VOID_STATUS_FAILED\x10\x03\x12\x1c\n\x18VOID_STATUS_NOT_REQUIRED\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payments.v1.common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOIDSTATUS']._serialized_start=471
  _globals['_VOIDSTATUS']._serialized_end=618
  _globals['_MONEY']._serialized_start=41
  _globals['_MONEY']._serialized_end=88
  _globals['_TIMESTAMP']._serialized_start=90
  _globals['_TIMESTAMP']._serialized_end=133
  _globals['_ADDRESS']._serialized_start=135
  _globals['_ADDRESS']._serialized_end=241
  _globals['_EVENTMETADATA']._serialized_start=243
  _globals['_EVENTMETADATA']._serialized_end=366
  _globals['_ERRORDETAILS']._serialized_start=368
  _globals['_ERRORDETAILS']._serialized_end=468
# @@protoc_insertion_point(module_scope)
